### ISSUE TITLE
Шрифты

### ISSUE THREAD

**Issue by foxhable** [momo-hash1/restaurant_valentino#18]
Это просто совет, не правка, делать не нужно. Закрой, как прочтешь
- Чтобы упростить работу с шрифтами можно одну семью шрифтов назвать одинаково и добавлять толщину со стилями в объявление шрифта. Например это:

```css
@font-face {
    font-family: "moniqa-paragraph";
    src: url("../../fonts/Moniqa-Paragraph.ttf");
}
@font-face {
    font-family: "moniqa-extralight";
    src: url("../../fonts/Moniqa-ExtraLightParagraph.ttf");
}
@font-face {
    font-family: "moniqa-light-italic";
    src: url("../../fonts/Moniqa-LightItalicDisplay.ttf");
}
@font-face {
    font-family: "moniqa-thincondensed";
    src: url("../../fonts/Moniqa-ThinCondensedDisplay.ttf");
}
@font-face {
    font-family: "moniqa-narrowparagraph";
    src: url("../../fonts/Moniqa-NarrowParagraph.ttf");
}
```

Должно превратиться в это:
```css
@font-face {
    font-family: "moniqa-paragraph";
    src: url("../../fonts/Moniqa-Paragraph.ttf");
}
@font-face {
    /* изменено имя */
    font-family: "moniqa";
    src: url("../../fonts/Moniqa-ExtraLightParagraph.ttf");
    /* Добавлены параметры */
    font-weight: 200;
}
@font-face {
    /* изменено имя */
    font-family: "moniqa";
    src: url("../../fonts/Moniqa-LightItalicDisplay.ttf");
    /* Добавлены параметры */
    font-weight: 200;
    font-style: italic;
}
@font-face {
    /* изменено имя */
    font-family: "moniqa";
    src: url("../../fonts/Moniqa-ThinCondensedDisplay.ttf");
    /* Добавлены параметры */
    font-weight: 100;
}
@font-face {
    font-family: "moniqa-narrowparagraph";
    src: url("../../fonts/Moniqa-NarrowParagraph.ttf");
}
```
