### ISSUE TITLE
Анимации

### ISSUE THREAD

**Issue by foxhable** [momo-hash1/restaurant_valentino#6]
Везде, где используешь анимации через css стили, добавляй `transition`, чтобы не было дерганых переходов. Например на `.button-circle` добавь
```css
.button-circle {
  transition-property: background, border-color;
  transition-duration: 300ms;
  transition-timing-function: ease-in-out;
}
```
